sonar.projectKey=juice-shop
sonar.projectName=OWASP Juice Shop
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.host.url=http://98.90.197.242:9000
sonar.login=sqp_0a440b96c1abe48584bee2bb575e695f73dcdce5
