name: SonarQube Scan

on:
  push:
    branches:
      - sonarqube

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://<your-aws-public-ip>:9000
          SONAR_PROJECT_KEY: juice-shop
